-- MySQL Script generated by MySQL Workbench
-- Thu Apr 25 06:04:38 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema Lizst
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Lizst` ;

-- -----------------------------------------------------
-- Schema Lizst
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Lizst` DEFAULT CHARACTER SET latin1 ;
USE `Lizst` ;

-- -----------------------------------------------------
-- Table `Lizst`.`CheckedOut`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Lizst`.`CheckedOut` ;

CREATE TABLE IF NOT EXISTS `Lizst`.`CheckedOut` (
  `MusicianId` INT(11) NOT NULL,
  `PartId` INT(11) NOT NULL,
  `DateOut` DATE NULL DEFAULT NULL,
  `DateDue` DATE NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `Lizst`.`Ensemble`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Lizst`.`Ensemble` ;

CREATE TABLE IF NOT EXISTS `Lizst`.`Ensemble` (
  `EnsembleId` INT(11) NOT NULL AUTO_INCREMENT,
  `EnsembleName` VARCHAR(255) NOT NULL,
  `Conductor` VARCHAR(255) NULL DEFAULT NULL,
  `Year` VARCHAR(5) NULL DEFAULT NULL,
  PRIMARY KEY (`EnsembleId`),
  UNIQUE INDEX `EnsembleId_UNIQUE` (`EnsembleId` ASC) VISIBLE,
  UNIQUE INDEX `EnsembleName_UNIQUE` (`EnsembleName` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 205
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `Lizst`.`Musician`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Lizst`.`Musician` ;

CREATE TABLE IF NOT EXISTS `Lizst`.`Musician` (
  `MusicianId` INT(11) NOT NULL AUTO_INCREMENT,
  `MusicianName` VARCHAR(255) NULL DEFAULT NULL,
  `Email` VARCHAR(255) NULL DEFAULT NULL,
  `Part` VARCHAR(255) NULL DEFAULT NULL,
  `StudentId` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`MusicianId`),
  UNIQUE INDEX `MusicianId_UNIQUE` (`MusicianId` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 636
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `Lizst`.`EnsemblePlayers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Lizst`.`EnsemblePlayers` ;

CREATE TABLE IF NOT EXISTS `Lizst`.`EnsemblePlayers` (
  `EnsembleId` INT(11) NULL DEFAULT NULL,
  `MusicianId` INT(11) NULL DEFAULT NULL,
  INDEX `EnsembleId` (`EnsembleId` ASC) VISIBLE,
  INDEX `MusicianId` (`MusicianId` ASC) VISIBLE,
  CONSTRAINT `EnsemblePlayers_ibfk_1`
    FOREIGN KEY (`EnsembleId`)
    REFERENCES `Lizst`.`Ensemble` (`EnsembleId`),
  CONSTRAINT `EnsemblePlayers_ibfk_2`
    FOREIGN KEY (`MusicianId`)
    REFERENCES `Lizst`.`Musician` (`MusicianId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `Lizst`.`Part`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Lizst`.`Part` ;

CREATE TABLE IF NOT EXISTS `Lizst`.`Part` (
  `PartId` INT(11) NOT NULL AUTO_INCREMENT,
  `PieceId` INT(11) NULL DEFAULT NULL,
  `Count` INT(11) NULL DEFAULT NULL,
  `Condition` INT(11) NULL DEFAULT NULL,
  `Part` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`PartId`),
  UNIQUE INDEX `PartId_UNIQUE` (`PartId` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `Lizst`.`Piece`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Lizst`.`Piece` ;

CREATE TABLE IF NOT EXISTS `Lizst`.`Piece` (
  `PieceId` INT(11) NOT NULL AUTO_INCREMENT,
  `NumberOfParts` INT(11) NULL DEFAULT NULL,
  `Instrument` VARCHAR(50) NULL DEFAULT NULL,
  `ScoreId` INT(11) NULL DEFAULT NULL,
  `Edition` VARCHAR(50) NULL DEFAULT NULL,
  `AggregateRating` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`PieceId`))
ENGINE = InnoDB
AUTO_INCREMENT = 795
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `Lizst`.`Score`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Lizst`.`Score` ;

CREATE TABLE IF NOT EXISTS `Lizst`.`Score` (
  `ScoreId` INT(11) NOT NULL AUTO_INCREMENT,
  `Title` VARCHAR(100) NOT NULL,
  `Composer` VARCHAR(40) NOT NULL,
  `Genre` VARCHAR(40) NOT NULL,
  `NumberOfParts` INT(11) NOT NULL,
  `SecondaryClassification` VARCHAR(40) NULL DEFAULT NULL,
  `Publisher` VARCHAR(40) NULL DEFAULT NULL,
  `InStock` VARCHAR(40) NULL DEFAULT NULL,
  `Notes` VARCHAR(250) NULL DEFAULT NULL,
  `sid` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`ScoreId`))
ENGINE = InnoDB
AUTO_INCREMENT = 336
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `Lizst`.`ScorePieces`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Lizst`.`ScorePieces` ;

CREATE TABLE IF NOT EXISTS `Lizst`.`ScorePieces` (
  `ScoreId` INT(11) NOT NULL,
  `PieceId` INT(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`PieceId`))
ENGINE = InnoDB
AUTO_INCREMENT = 31
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `Lizst`.`Test`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Lizst`.`Test` ;

CREATE TABLE IF NOT EXISTS `Lizst`.`Test` (
  `ID` INT(11) NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `Lizst`.`testScores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Lizst`.`testScores` ;

CREATE TABLE IF NOT EXISTS `Lizst`.`testScores` (
  `title` VARCHAR(50) NOT NULL,
  `composer` VARCHAR(50) NULL DEFAULT NULL,
  `genre` VARCHAR(50) NULL DEFAULT NULL,
  `date_checked_out` DATE NOT NULL,
  `due_date` DATE NOT NULL,
  `number_of_parts` INT(11) NULL DEFAULT NULL,
  `id` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
