// <auto-generated />
using System;
using Lizst.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Lizst.Migrations
{
    [DbContext(typeof(LizstContext))]
    partial class LizstContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028");

            modelBuilder.Entity("Lizst.Models.Test", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Composer");

                    b.Property<DateTime>("DateCheckedOut");

                    b.Property<DateTime>("DueDate");

                    b.Property<string>("Genre");

                    b.Property<int>("NumberOfParts");

                    b.Property<string>("Title");

                    b.HasKey("ID");

                    b.ToTable("Test");
                });
#pragma warning restore 612, 618
        }
    }
}
